### ISSUE TITLE
Where should skip connections go?

### ISSUE THREAD

**Issue by dfrumkin** [avinashpaliwal/Super-SloMo#50]
I see that your skip connections go into the second layer of each "up" block.  According to the paper, it seems they should go into the first one.  Not sure how important this is, but what's your take on this?

**Comment by avinashpaliwal** [comment]
Hi. That's a good catch. This was my first deep learning project and I was trying to understand the UNet architecture. I don't remember completely but I think based on the understanding from some sources, I assumed this as the implementation. But maybe the skip connection has to be concatenated to the first conv layer's input. I think I was trying to concatenate e.g. 32 skip channels with 32 channels output of first conv layer instead of 64 channels of upsampled layer. But I don't think this would make a huge difference in the performance of the model.
