### ISSUE TITLE
Why Are fps And sf Setting Separate And Update ReadMe

### ISSUE THREAD

**Issue by MatteCrystal** [avinashpaliwal/Super-SloMo#82]
Could someone explain why and how the fps and sf settings are separate? In the readme it simply shows a easy example of how you should set these variables but on the surface It seems kinda redundant and adds confusion/user error. If you have a 10 sec 30fps video 300 frames total and you want to multiply  it by 3 then by default you would expect 90fps and 900 frames total. So what benefit/reasons is their for making us provide both the multiplication factor and fps.  It seems like something that would just lead to mistakes like stating 60fps when it was supposed to be 90fps. 

If their are particular scenarios where someone would purposefully not keep these values lined up then what would they be? wouldn't it just be better to just automatically calculate the correct video fps unless a specific fps was explicitly passed?

I think adding this info into the readme or as a link someone can follow from within the readme will be helpful. To myself and others.

**Comment by Thomasedv** [comment]
Well it comes down to it that this is called super slow mo, and that this way is simply easier. 
Making it easy to double framerate or make it slowmotion by doubling frames and keeping the playback is convenient. 

But i think the main reason it's done, is because it's easy this way, you tell it how many intermediate frames you want (sf) and the final video fps. Without the user telling the program the target framerate, it would have to find that framerate in the original video as well. ffmpeg only extract images and then converts the new images into a video with the user specified framerate. The other case would be to detect framerate with ffprobe for example, putting the burden on the user to supply the path to that as well when running the script.

**Comment by avinashpaliwal** [comment]
@Thomasedv is right. They stand for two different settings. You can either create a slow motion video by keeping the original frame rate or a high fps smooth video (like 120fps).
